export const EXPLORE_POSTS_REQUEST = 'EXPLORE_POSTS_REQUEST';
export const EXPLORE_POSTS_SUCCESS = 'EXPLORE_POSTS_SUCCESS';
export const EXPLORE_POSTS_FAILURE = 'EXPLORE_POSTS_FAILURE';

export const FOLLOWING_POSTS_REQUEST = 'FOLLOWING_POSTS_REQUEST';
export const FOLLOWING_POSTS_SUCCESS = 'FOLLOWING_POSTS_SUCCESS';
export const FOLLOWING_POSTS_FAILURE = 'FOLLOWING_POSTS_FAILURE';

export const CREATE_NEW_POST_REQUEST = 'CREATE_NEW_POST_REQUEST';
export const CREATE_NEW_POST_SUCCESS = 'CREATE_NEW_POST_SUCCESS';
export const CREATE_NEW_POST_FAILURE = 'CREATE_NEW_POST_FAILURE';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAILURE = 'POST_DETAILS_FAILURE';

export const LIKE_POST_FROM_FEED_REQUEST = 'LIKE_POST_FROM_FEED_REQUEST';
export const LIKE_POST_FROM_FEED_SUCCESS = 'LIKE_POST_FROM_FEED_SUCCESS';
export const LIKE_POST_FROM_FEED_FAILURE = 'LIKE_POST_FROM_FEED_FAILURE';
export const CLEAR_LIKE_POST_DATA = 'CLEAR_LIKE_POST_DATA';

export const LIKE_POST_FROM_DETAILS_REQUEST = 'LIKE_POST_FROM_DETAILS_REQUEST';
export const LIKE_POST_FROM_DETAILS_SUCCESS = 'LIKE_POST_FROM_DETAILS_SUCCESS';
export const LIKE_POST_FROM_DETAILS_FAILURE = 'LIKE_POST_FROM_DETAILS_FAILURE';

export const GET_LIKED_POSTS_REQUEST = 'GET_LIKED_POSTS_REQUEST';
export const GET_LIKED_POSTS_SUCCESS = 'GET_LIKED_POSTS_SUCCESS';
export const GET_LIKED_POSTS_FAILURE = 'GET_LIKED_POSTS_FAILURE';

export const SAVE_POST_REQUEST = 'SAVE_POST_REQUEST';
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS';
export const SAVE_POST_FAILURE = 'SAVE_POST_FAILURE';

export const GET_SAVED_POSTS_REQUEST = 'GET_SAVED_POSTS_REQUEST';
export const GET_SAVED_POSTS_SUCCESS = 'GET_SAVED_POSTS_SUCCESS';
export const GET_SAVED_POSTS_FAILURE = 'GET_SAVED_POSTS_FAILURE';

export const COMMENT_POST_REQUEST = 'COMMENT_POST_REQUEST';
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS';
export const COMMENT_POST_FAILURE = 'COMMENT_POST_FAILURE';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';
