export const USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE';

export const COMPLETE_SIGN_UP_REQUEST = 'COMPLETE_SIGN_UP_REQUEST';
export const COMPLETE_SIGN_UP_SUCCESS = 'COMPLETE_SIGN_UP_SUCCESS';
export const COMPLETE_SIGN_UP_FAILURE = 'COMPLETE_SIGN_UP_FAILURE';
export const CLEAR_SIGN_UP_DATA = 'CLEAR_SIGN_UP_DATA';

export const GET_USER_PUSH_TOKEN_REQUEST = 'GET_USER_PUSH_TOKEN_REQUEST';
export const GET_USER_PUSH_TOKEN_SUCCESS = 'GET_USER_PUSH_TOKEN_SUCCESS';
export const GET_USER_PUSH_TOKEN_FAILURE = 'GET_USER_PUSH_TOKEN_FAILURE';

export const AUTH_USER_DETAILS_REQUEST = 'AUTH_USER_DETAILS_REQUEST';
export const AUTH_USER_DETAILS_SUCCESS = 'AUTH_USER_DETAILS_SUCCESS';
export const AUTH_USER_DETAILS_FAILURE = 'AUTH_USER_DETAILS_FAILURE';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE';

export const AUTH_USER_POSTS_REQUEST = 'AUTH_USER_POSTS_REQUEST';
export const AUTH_USER_POSTS_SUCCESS = 'AUTH_USER_POSTS_SUCCESS';
export const AUTH_USER_POSTS_FAILURE = 'AUTH_USER_POSTS_FAILURE';

export const USER_POSTS_REQUEST = 'USER_POSTS_REQUEST';
export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS';
export const USER_POSTS_FAILURE = 'USER_POSTS_FAILURE';
export const CLEAR_POSTS_DATA = 'CLEAR_POSTS_DATA';

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';
export const CLEAR_PROFILE_DATA = 'CLEAR_PROFILE_DATA';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';
export const CLEAR_PASSWORD_DATA = 'CLEAR_PASSWORD_DATA';

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';

export const VIEW_NOTIFICATION_REQUEST = 'VIEW_NOTIFICATION_REQUEST';
export const VIEW_NOTIFICATION_SUCCESS = 'VIEW_NOTIFICATION_SUCCESS';
export const VIEW_NOTIFICATION_FAILURE = 'VIEW_NOTIFICATION_FAILURE';

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE';

export const VIEW_FOLLOWERS_REQUEST = 'VIEW_FOLLOWERS_REQUEST';
export const VIEW_FOLLOWERS_SUCCESS = 'VIEW_FOLLOWERS_SUCCESS';
export const VIEW_FOLLOWERS_FAILURE = 'VIEW_FOLLOWERS_FAILURE';

export const VIEW_FOLLOWING_REQUEST = 'VIEW_FOLLOWING_REQUEST';
export const VIEW_FOLLOWING_SUCCESS = 'VIEW_FOLLOWING_SUCCESS';
export const VIEW_FOLLOWING_FAILURE = 'VIEW_FOLLOWING_FAILURE';
